from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outPutLabel = QtWidgets.QLabel(self.centralwidget)
        self.outPutLabel.setGeometry(QtCore.QRect(10, 11, 340, 90))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outPutLabel.setFont(font)
        self.outPutLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outPutLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outPutLabel.setLineWidth(2)
        self.outPutLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outPutLabel.setObjectName("outPutLabel")
        self.remainButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("%"))
        self.remainButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.remainButton.setFont(font)
        self.remainButton.setObjectName("remainButton")
        self.CButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("C"))
        self.CButton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.CButton.setFont(font)
        self.CButton.setObjectName("CButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.removeChar())
        self.arrowButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.Button9 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("9"))
        self.Button9.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button9.setFont(font)
        self.Button9.setObjectName("Button9")
        self.Button7 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("7"))
        self.Button7.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button7.setFont(font)
        self.Button7.setObjectName("Button7")
        self.Button8 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("8"))
        self.Button8.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button8.setFont(font)
        self.Button8.setObjectName("Button8")
        self.multiButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("*"))
        self.multiButton.setGeometry(QtCore.QRect(275, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiButton.setFont(font)
        self.multiButton.setObjectName("multiButton")
        self.Button6 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("6"))
        self.Button6.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button6.setFont(font)
        self.Button6.setObjectName("Button6")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("4"))
        self.Button4.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button4.setFont(font)
        self.Button4.setObjectName("Button4")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("5"))
        self.Button5.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button5.setFont(font)
        self.Button5.setObjectName("Button5")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(270, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("3"))
        self.Button3.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button3.setFont(font)
        self.Button3.setObjectName("Button3")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("1"))
        self.Button1.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button1.setFont(font)
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("2"))
        self.Button2.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button2.setFont(font)
        self.Button2.setObjectName("Button2")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(270, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.dot_it())
        self.dotButton.setGeometry(QtCore.QRect(190, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dotButton.setFont(font)
        self.dotButton.setObjectName("dotButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.Button0 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.press_it("0"))
        self.Button0.setGeometry(QtCore.QRect(100, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button0.setFont(font)
        self.Button0.setObjectName("Button0")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda :self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(270, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def math_it(self):
        screen =self.outPutLabel.text()
        ansewr =eval(screen)
        self.outPutLabel.setText(f'{ansewr}')
        
    
    def dot_it(self):
        screen =self.outPutLabel.text()
        
        if screen[-1]=="." :
            pass
        else:
            self.outPutLabel.setText(f'{screen}.')

    
    def removeChar(self):
        screen =self.outPutLabel.text()
        screen =screen[:-1]
        self.outPutLabel.setText(screen)

    def plus_minus_it(self):
        screen = self.outPutLabel.text()
        if '-' in screen:
            self.outPutLabel.setText(screen.replace("-",""))
        else : 
            self.outPutLabel.setText(f'-{screen}')
            

    def press_it(self,pressed):
        if pressed =="C":
            self.outPutLabel.setText("0")
        else:
            if self.outPutLabel.text()=='0':
                self.outPutLabel.setText('')
            self.outPutLabel.setText(f'{self.outPutLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outPutLabel.setText(_translate("MainWindow", "0"))
        self.remainButton.setText(_translate("MainWindow", "%"))
        self.CButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.multiButton.setText(_translate("MainWindow", "*"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.plusminusButton.setText(_translate("MainWindow", "-/+"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.equalButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
